name: Cleanup Old Workflow Runs

on:
  schedule:
    # 每周日凌晨 2 点运行
    - cron: '0 2 * * 0'
  workflow_dispatch:
    inputs:
      days_old:
        description: '删除超过多少天的记录'
        required: true
        default: '3'
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: Cleanup workflow runs
        run: |
          # 设置默认值
          DAYS_OLD=${DAYS_OLD:-30}
          
          # 获取所有 workflow 运行记录
          echo "正在删除超过 $DAYS_OLD 天的 workflow 运行记录..."
          
          # 使用 GitHub CLI 删除旧记录
          gh run list --json databaseId,createdAt,workflowName --jq ".[] | select(.createdAt < (now - $DAYS_OLD*24*60*60)) | .databaseId" | xargs -I {} gh run delete {} --yes
          
          echo "清理完成！"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAYS_OLD: ${{ inputs.days_old }}